fix: Add missing host_callbacks.h include in ui_screens.c
The function host_submit_login_pin() is declared in host_callbacks.h
but ui_screens.c was not including this header, causing an implicit
declaration error at compile time.

Added #include "host_callbacks.h" after #include "host.h" to make
the function declaration visible to ui_screens.c.

This fixes the build error:
  error: implicit declaration of function 'host_submit_login_pin'